# Generated by Django 2.2.4 on 2023-06-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dojo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ninjas', to='Dojo_app.Dojo'),
        ),
    ]
