print("Hello World")
name=("Mahmoud")
number = 5
food= ("Sushi" , "Tavuk Şiş")
print("My name is", name)
print("Hello "+ name)
print("Hello",number)
print(f"Hello "+ "number")
print("I Love to eat " ,food[0],"and", food[1])
print(f'I Love to eat {food[0]} and {food[1]}')
